const roomTypeActionTypes = {

    FETCHING_ROOM_TYPES: "FETCHING_ROOM_TYPES",
    FETCHING_FINISHED: "FETCHING_FINISHED",

    SET_SINGLE_ROOM_TYPE: "SET_SINGLE_ROOM_TYPE",
    CLEAR_SINGLE_ROOM_TYPE: "CLEAR_SINGLE_ROOM_TYPE",

    ROOM_TYPE_REQUEST: "ROOM_TYPE_REQUEST",
    ROOM_TYPE_REQUEST_FINISHED: "ROOM_TYPE_REQUEST_FINISHED",

    SET_ROOM_TYPES_LIST: "SET_ROOM_TYPES_LIST"
};

export default roomTypeActionTypes;