const hotelActionTypes = {
    FETCHING_DETAILS: "FETCHING_DETAILS",
    FETCHING_DONE: "FETCHING_DONE",
    STORE_DETAILS: "STORE_DETAILS",
    HOTEL_REQUEST: "HOTEL_REQUEST",
    HOTEL_REQUEST_FINISHED: "HOTEL_REQUEST_FINISHED",
    STORE_HOTELS_LIST: "STORE_HOTELS_LIST"
};

export default hotelActionTypes;