const bookingActionTypes = {

    FETCHING_SINGLE_BOOKING: "FETCHING_SINGLE_BOOKING",
    FETCHING_FINISHED: "FETCHING_FINISHED",

    SET_SINGLE_BOOKING: "SET_SINGLE_BOOKING",
    CLEAR_SINGLE_BOOKING: "CLEAR_SINGLE_BOOKING",

    BOOKING_REQUEST: "BOOKING_REQUEST",
    BOOKING_REQUEST_FINISHED: "BOOKING_REQUEST_FINISHED"

};

export default bookingActionTypes;