const priceListActionTypes = {

    FETCHING_PRICE_LIST: "FETCHING_PRICE_LIST",
    FETCHING_FINISHED: "FETCHING_FINISHED",

    SET_SINGLE_PRICE: "SET_SINGLE_PRICE",
    CLEAR_SINGLE_PRICE: "CLEAR_SINGLE_PRICE",

    PRICE_REQUEST: "PRICE_REQUEST",
    PRICE_REQUEST_FINISHED: "PRICE_REQUEST_FINISHED"

};

export default priceListActionTypes;