const roomActionTypes = {
    FETCH_ROOM_TYPES_LIST: "FETCH_ROOM_TYPES_LIST",
    ROOM_REQUEST: "ROOM_REQUEST",
    ROOM_REQUEST_FINISHED: "ROOM_REQUEST_FINISHED",
    ROOM_CREATED: "ROOM_CREATED",
    ROOM_UPDATED: "ROOM_UPDATED",

    FETCH_ROOM: "FETCH_ROOM",
    FETCHING_FINISHED: "FETCHING_FINISHED",
    SET_SINGLE_ROOM: "SET_SINGLE_ROOM",

    FETCHING_ROOMS_LIST: "FETCHING_ROOMS_LIST",
    SET_ROOMS_LIST: "SET_ROOMS_LIST"

};

export default roomActionTypes;